# Generated by Django 5.2.3 on 2025-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_authorizedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='installation_cost_per_watt',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Installation cost per watt in USD', max_digits=5),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='price_per_watt',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Price per watt in USD', max_digits=5),
        ),
    ]
