# Generated by Django 5.2.8 on 2025-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_serviceprovider_installation_cost_per_watt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='business_description',
            field=models.TextField(blank=True, help_text='Describe your business and services'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='business_hours',
            field=models.CharField(blank=True, help_text='e.g., Mon-Fri 9AM-5PM', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='certifications',
            field=models.TextField(blank=True, help_text='List your certifications'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_logos/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='insurance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_areas',
            field=models.TextField(blank=True, help_text='Cities/regions you serve, comma-separated'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_radius',
            field=models.IntegerField(default=50, help_text='Service radius in miles'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='years_in_business',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
    ]
