# Generated by Django 5.2.8 on 2025-11-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_serviceprovider_business_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('power_watts', models.IntegerField()),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, help_text='Panel efficiency in fraction, e.g., 0.20', max_digits=4, null=True)),
                ('price_pkr', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('warranty_years', models.IntegerField(default=0, help_text='Warranty period in years')),
                ('image', models.ImageField(blank=True, null=True, upload_to='provider_panels/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='solar.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
