# Generated by Django 5.2.8 on 2025-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_providerpanel_model_no_length_width_installation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpanel',
            name='panel_type',
            field=models.CharField(blank=True, choices=[('premium', 'Premium Solar Panel'), ('large', 'Large Solar Panel'), ('medium', 'Medium Solar Panel'), ('standard', 'Standard Solar Panel')], help_text='Predefined panel type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_panel_type',
            field=models.CharField(blank=True, choices=[('premium', 'Premium Solar Panel'), ('large', 'Large Solar Panel'), ('medium', 'Medium Solar Panel'), ('standard', 'Standard Solar Panel')], help_text="User's preferred panel type", max_length=20, null=True),
        ),
    ]
