# Generated by Django 5.2.8 on 2025-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_providerpanel_panel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerpanel',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerpanel',
            name='panel_type',
            field=models.CharField(blank=True, choices=[('premium', 'Premium Solar Panel'), ('large', 'Large Solar Panel'), ('medium', 'Medium Solar Panel'), ('standard', 'Standard Solar Panel')], help_text='Select panel type', max_length=20, null=True),
        ),
    ]
