# Generated by Django 5.2.8 on 2025-11-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_alter_providerpanel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity for purchase'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_category',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase Panels'), ('installation', 'Installation Service'), ('repair', 'Repair Service'), ('maintenance', 'Maintenance Service')], help_text='Main request type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='selected_panel',
            field=models.ForeignKey(blank=True, help_text='Selected panel for purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.providerpanel'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='preferred_panel_type',
            field=models.CharField(blank=True, choices=[('premium', 'Premium Solar Panel'), ('large', 'Large Solar Panel'), ('medium', 'Medium Solar Panel'), ('standard', 'Standard Solar Panel')], help_text='Panel type for installation/maintenance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
